services:
  dsproxy:
    image: ghcr.io/mewisme/dsproxy:latest
    pull_policy: always
    container_name: dsproxy
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-9999}:9999"
    env_file:
      - .env
    volumes:
      - dsproxy-cache:/home/nonroot/.dsproxy
    networks:
      - dsproxy-network

volumes:
  dsproxy-cache:

networks:
  dsproxy-network:
    driver: bridge
